apiVersion: v1
kind: ServiceAccount
metadata:
  name: spanner-agent-sa
  namespace: default
  annotations:
    # Workload Identity annotation - maps KSA to GCP service account
    iam.gke.io/gcp-service-account: spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com
    # Description for the service account
    description: "Service account for Spanner Agent with least-privilege access"
    # Security labels
    security.kubernetes.io/least-privilege: "true"
    security.kubernetes.io/read-only-operations: "true"
---
# GCP IAM Service Account (created via gcloud)
# This service account will be created with the following command:
# gcloud iam service-accounts create spanner-agent-sa \
#   --display-name="Spanner Agent Service Account" \
#   --description="Service account for Spanner Agent with least-privilege access"
#
# IAM Roles to be assigned (least privilege):
# 1. roles/spanner.databaseViewer - Read-only access to Spanner databases
# 2. roles/aiplatform.user - Access to Vertex AI for LLM operations
# 3. roles/logging.logWriter - Write audit logs to Cloud Logging
# 4. roles/monitoring.metricWriter - Write metrics to Cloud Monitoring
#
# Commands to assign roles:
# gcloud projects add-iam-policy-binding extreme-gecko-466211-t1 \
#   --member="serviceAccount:spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com" \
#   --role="roles/spanner.databaseViewer"
#
# gcloud projects add-iam-policy-binding extreme-gecko-466211-t1 \
#   --member="serviceAccount:spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com" \
#   --role="roles/aiplatform.user"
#
# gcloud projects add-iam-policy-binding extreme-gecko-466211-t1 \
#   --member="serviceAccount:spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com" \
#   --role="roles/logging.logWriter"
#
# gcloud projects add-iam-policy-binding extreme-gecko-466211-t1 \
#   --member="serviceAccount:spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com" \
#   --role="roles/monitoring.metricWriter"
#
# Enable Workload Identity binding:
# gcloud iam service-accounts add-iam-policy-binding \
#   spanner-agent-sa@extreme-gecko-466211-t1.iam.gserviceaccount.com \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:extreme-gecko-466211-t1.svc.id.goog[default/spanner-agent-sa]" 